#pragma once
#define STATUS_SEUCCESS_FOUND_FILE 210
#define STATUS_SEUCCESS_LIST_CREATED 211
#define STATUS_FAIL_FILE_NOT_FOUND 1001
#define STATUS_FAIL_NO_FILES 1002
#define STATUS_FAIL_SERVER_ERROR 1003
